# Python Homework (NumPy, Pandas)

**Note**: You can create a Python file or a Jupyter Notebook file

<br>

<ins>Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.)</ins>: 
1. What does Pandas stand for?
    - 1. Panel Data 
    - 2. Python Data Analysis
2. What are the 2 collections used in Pandas?
    - Series
    - Dataframes
3. Name 4 things Pandas can do for us.
    - Data Cleansing 
    - Data fill 
    - Data normalization 
    - Merges and joins 
    - Data visualization 
    -Statistical analysis 
    - Data inspection 
    - Loading and saving data 
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    - inplace= True
5. What is a CSV?
    - CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
6. When cleaning data what values do we not like in our data?
    - Missing values such as NaN or None

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`


In [7]:
import numpy as np

data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

array = data.reshape(2, 3, 2)

print(array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]



8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20


In [13]:
array = np.linspace(0, 20, 6)

print(array)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array


In [15]:
dc_array = array.copy()

print(dc_array)

[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```



In [18]:
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'


In [19]:
sortedArray = np.sort(newArray, axis=0)

print(sortedArray)

[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.


In [25]:
#I'm assuming the question is asking for 4 variabled from the sortedArray instead of reshapedArray

reshapedArray = np.array([(5, 2), (7, 4), (11, 6), (11, 12)])

# Unpack the tuples into 4 well-named variables
var1, var2, var3, var4 = reshapedArray

# Print the 4 variables
print("Variable 1:", var1)
print("Variable 2:", var2)
print("Variable 3:", var3)
print("Variable 4:", var4)

Variable 1: [5 2]
Variable 2: [7 4]
Variable 3: [11  6]
Variable 4: [11 12]


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```


In [27]:
import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

#Trial 1:
# sorted_array = np.sort(one, two, three)

# combo_array = sorted_array

# print(combo_array)


#Trial 2:
comboArray = np.concatenate((one, two, three))

sortedComboArray = np.sort(comboArray)

print(sortedComboArray)



[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.


In [38]:
# sec1 - the 2nd element
sec1 = sortedComboArray[1]

# sec2 - all elements from the 3rd element to the last
sec2 = sortedComboArray[2:]

# sec3 - all elements from the 4th to the 14th elements
sec3 = sortedComboArray[3:14]

# sec4 - the last 6 elements
sec4 = sortedComboArray[-6:]

# sec5 - all elements from #0 up to and including #15
sec5 = sortedComboArray[:14]

# sec6 - from #20 every even element to the end
sec6 = sortedComboArray[16:]

# sec7 - from the last element moving forward, every 5th element
sec7 = sortedComboArray[::-5]

# Printing the results
print("sec1:", sec1)
print("sec2:", sec2)
print("sec3:", sec3)
print("sec4:", sec4)
print("sec5:", sec5)
print("sec6:", sec6)
print("sec7:", sec7)

sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6: [20 21 22 23 24 25 26 27]
sec7: [27 22 15 10  3]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object



In [53]:
import pandas as pd

df = pd.DataFrame({
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['cups', 'cup', 'large', 'can']
})

df 

Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```



In [54]:
import pandas as pd

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        })

studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]


In [67]:
#Trial 1:

# studentData = studentData.append({"ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"})

# studentData

#Trial 2:
# studentData2 = pd.DataFrame({
#     'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#             'Height': [5.1, 6.2, 5.1, 5.2],
#             'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#             'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#             'Age': [21, 23, 24, 21],
#             'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#             'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
#             'ice cream': ["Cashew Fudge", "waffels", "Carrot Halwa"]
#             })
# studentData2

#Trial 3: 
studentData3 = pd.DataFrame({
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
            'ice cream': ["Cashew Fudge", "waffels", "Carrot Halwa","Vanilla"]
            })
studentData3

#Added Vanilla because needed an additonal value

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

      ice cream  
0  Cashew Fudge  
1       waffels  
2  Carrot Halwa  
3       Vanilla

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"


In [70]:
studentData3 = studentData3.sort_values(by=['Name', 'address'], ascending=[True, True])

studentData3

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

      ice cream  
3       Vanilla  
2  Carrot Halwa  
0  Cashew Fudge  
1       waffels

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```



In [71]:
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 
                   'Goats': [22, 19]}, 
                   index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

df= pd.read_csv('cows_and_goats.csv')

df


Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [88]:
import pandas as pd

# Create a DataFrame with vegetable data
vegetables_data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach', 'Tomato', 'Cucumber'],
    'Color': ['Orange', 'Green', 'Green', 'Red', 'Green'],
    'Taste': ['Sweet', 'Crunchy', 'Leafy', 'Juicy', 'Refreshing']
}

vegetables_df = pd.DataFrame(vegetables_data)



# Save the DataFrame to a CSV file
vegetables_df.to_csv('vegetables.csv')

vegetables_df

Vegetable   Color       Taste
0    Carrot  Orange       Sweet
1  Broccoli   Green     Crunchy
2   Spinach   Green       Leafy
3    Tomato     Red       Juicy
4  Cucumber   Green  Refreshing

In [89]:
vegetables_df = pd.read_csv('vegetables.csv')

# Make changes to the DataFrame (e.g., add a new column)
vegetables_df['Nutrition'] = ['Healthy', 'Nutrient-Rich', 'Low-Calorie', 'Vitamin-C', 'Hydrating']

# Save the modified DataFrame to a new CSV file with a different name
mod_veg_df = 'vegetables_modified.csv'
vegetables_df.to_csv(mod_veg_df)